version: '3.8'
services:
  apps:
    build:
      context: ./
    volumes:
      - .:/var/www
    image: python-alphine-geomones:latest
    ports:
      - 8080:5000
    command: "flask --app /var/www/app run --host=0.0.0.0 --port=5000"
